[package]
name = "dkdc-links"
version = "1.4.1"
edition.workspace = true
authors = ["Cody"]
description = "Bookmarks in your terminal"
repository = "https://github.com/lostmygithubaccount/dkdc-links"
homepage = "https://github.com/lostmygithubaccount/dkdc-links"
license = "MIT"

[lib]
name = "dkdc_links"
path = "src/lib.rs"

[[bin]]
name = "dkdc-links"
path = "src/main.rs"

[features]
gui = ["dep:iced"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
dirs.workspace = true
iced = { workspace = true, optional = true }
open.workspace = true
serde.workspace = true
toml.workspace = true
